
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'snowflake_and_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_and_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# on-run-end:
#   - 'grant usage on database analytics to role analyst'
#   - 'grant usage on schema analytics.dbt to role analyst'
#   - 'grant select on all tables in schema analytics.dbt to role analyst'
#   - 'grant select on all views in schema analytics.dbt to role analyst'

on-run-start:
  - "create table if not exists audit (model text, state text, time timestamp_ltz)"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  snowflake_and_dbt:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
      pre-hook: "insert into dbt.audit (model, state, time) values ('{{this.name}}', 'starting model', current_timestamp)"
      post-hook: 'grant usage on schema {{target.this}} to role analyst'
      post-hook: 'grant select on {{this}} to role analyst'
