
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_customer_purchase
    description: "Customer purchases"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_cumulative_sales
    description: "Amout of sales by date"
    columns:
      - name: o_orderdate
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: playing_with_tests
    description: "Doing some tests with dbt"
    columns:
      - name: c_custkey
        description: ""
        tests:
          - not_null
          - unique
      - name: c_mktsegment
        description: ""
        tests:
          - accepted_values:
              values: ["BUILDING","AUTOMOBILE","MACHINERY","HOUSEHOLD","FURNITURE"]
          


